# Generated by Django 4.0 on 2022-01-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('slug', models.SlugField()),
            ],
        ),
    ]
