# Generated by Django 4.0 on 2022-01-18 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_input_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='input_by',
        ),
    ]
